export const games = [
    {
      id: 1,
      name: 'Game 1',
      price: '$59.99',
      description: 'An action-packed adventure game with stunning visuals.',
      rating: '4.7',
      releaseDate: '2023-01-15',
      image: '${process.env.PUBLIC_URL}/images/game1.jpg',
    },
    {
      id: 2,
      name: 'Game 2',
      price: '$49.99',
      description: 'A strategy game that tests your tactical skills.',
      rating: '4.5',
      releaseDate: '2023-02-20',
      image: '${process.env.PUBLIC_URL}/images/game2.jpg',
    },
    {
      id: 3,
      name: 'Game 3',
      price: '$39.99',
      description: 'A fast-paced racing game with immersive environments.',
      rating: '4.2',
      releaseDate: '2023-03-18',
      image: '${process.env.PUBLIC_URL}/images/game3.jpg',
    },
    {
      id: 4,
      name: 'Game 4',
      price: '$29.99',
      description: 'An indie game with a unique story and art style.',
      rating: '4.3',
      releaseDate: '2023-04-12',
      image: '${process.env.PUBLIC_URL}/images/game4.jpg',
    },
    {
      id: 5,
      name: 'Game 5',
      price: '$19.99',
      description: 'A puzzle game that challenges your problem-solving skills.',
      rating: '3.9',
      releaseDate: '2023-05-25',
      image: '${process.env.PUBLIC_URL}/images/game5.jpg',
    },
    {
      id: 6,
      name: 'Game 6',
      price: '$44.99',
      description: 'A sci-fi shooter set in a distant galaxy.',
      rating: '4.6',
      releaseDate: '2023-06-10',
      image: '${process.env.PUBLIC_URL}/images/game6.jpg',
    },
    {
      id: 7,
      name: 'Game 7',
      price: '$34.99',
      description: 'A survival game where resource management is key.',
      rating: '4.1',
      releaseDate: '2023-07-05',
      image: '${process.env.PUBLIC_URL}/images/game7.jpg',
    },
    {
      id: 8,
      name: 'Game 8',
      price: '$24.99',
      description: 'A role-playing game with deep character customization.',
      rating: '4.0',
      releaseDate: '2023-08-01',
      image: '${process.env.PUBLIC_URL}/images/game8.jpg',
    },
    {
      id: 9,
      name: 'Game 9',
      price: '$29.99',
      description: 'A stealth game that rewards patience and precision.',
      rating: '4.4',
      releaseDate: '2023-09-07',
      image: '${process.env.PUBLIC_URL}/images/game9.jpg',
    },
    {
      id: 10,
      name: 'Game 10',
      price: '$39.99',
      description: 'A sports game with realistic physics and gameplay.',
      rating: '4.2',
      releaseDate: '2023-10-15',
      image: '${process.env.PUBLIC_URL}/images/game10.jpg',
    },
    {
      id: 11,
      name: 'Game 11',
      price: '$19.99',
      description: 'A platformer with challenging levels and vibrant visuals.',
      rating: '3.8',
      releaseDate: '2023-11-05',
      image: '${process.env.PUBLIC_URL}/images/game11.jpg',
    },
    {
      id: 12,
      name: 'Game 12',
      price: '$49.99',
      description: 'An open-world RPG with endless exploration possibilities.',
      rating: '4.7',
      releaseDate: '2023-12-01',
      image: '${process.env.PUBLIC_URL}/images/game12.jpg',
    },
    {
      id: 13,
      name: 'Game 13',
      price: '$54.99',
      description: 'An epic fantasy game with massive battles and magic.',
      rating: '4.8',
      releaseDate: '2023-12-15',
      image: '${process.env.PUBLIC_URL}/images/game13.jpg',
    },
    {
      id: 14,
      name: 'Game 14',
      price: '$39.99',
      description: 'A detective game with a gripping storyline.',
      rating: '4.5',
      releaseDate: '2023-12-20',
      image: '${process.env.PUBLIC_URL}/images/game14.jpg',
    },
    {
      id: 15,
      name: 'Game 15',
      price: '$34.99',
      description: 'A simulation game where you manage a thriving city.',
      rating: '4.1',
      releaseDate: '2023-12-25',
      image: '${process.env.PUBLIC_URL}/images/game15.jpg',
    },
    {
      id: 16,
      name: 'Game 16',
      price: '$54.99',
      description: 'An epic medieval strategy game with massive battles.',
      rating: '4.8',
      releaseDate: '2023-11-10',
      image: '${process.env.PUBLIC_URL}/images/game16.jpg',
    },
    {
      id: 17,
      name: 'Game 17',
      price: '$24.99',
      description: 'A quirky indie game with a unique art style.',
      rating: '3.9',
      releaseDate: '2023-10-25',
      image: '${process.env.PUBLIC_URL}/images/game17.jpg',
    },
    {
      id: 18,
      name: 'Game 18',
      price: '$12.99',
      description: 'A puzzle-platformer that challenges your problem-solving skills.',
      rating: '4.2',
      releaseDate: '2023-09-05',
      image: '${process.env.PUBLIC_URL}/images/game18.jpg',
    },
    {
      id: 19,
      name: 'Game 19',
      price: '$29.99',
      description: 'A stealth game where patience and precision are key.',
      rating: '4.5',
      releaseDate: '2023-10-15',
      image: '${process.env.PUBLIC_URL}/images/game1.jpg',
    },
    {
      id: 20,
      name: 'Game 20',
      price: '$39.99',
      description: 'An exploration game with beautiful environments to discover.',
      rating: '4.7',
      releaseDate: '2023-11-20',
      image: '${process.env.PUBLIC_URL}/images/game2.jpg',
    },
  ];
  